# Generated by Django 4.2.8 on 2025-01-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=500)),
                ('bio', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
                'db_table': 'shop',
            },
        ),
        migrations.CreateModel(
            name='ShopTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField(default=None)),
                ('percent', models.FloatField(default=0.0)),
                ('status', models.CharField(default='before_of_time', max_length=100)),
            ],
            options={
                'verbose_name': 'shop_topic',
                'verbose_name_plural': 'shop_topics',
                'db_table': 'shop_topic',
            },
        ),
    ]
