# Generated by Django 4.2.8 on 2024-11-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=500)),
                ('bio', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
                'db_table': 'shop',
            },
        ),
    ]
