# Generated by Django 4.2.8 on 2024-11-24 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
