# Generated by Django 4.2.8 on 2025-02-23 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoptopic',
            name='midlevel_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_midlevel_topic_topic', to='Product.midleveltopic'),
        ),
    ]
