# Generated by Django 4.2.8 on 2025-02-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'provider',
                'verbose_name_plural': 'providers',
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='ProviderBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('api_url', models.CharField(max_length=500)),
                ('percent', models.FloatField(default=0.0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_branch', to='Admin.provider')),
            ],
            options={
                'verbose_name': 'provider_branch',
                'verbose_name_plural': 'provider_branchs',
                'db_table': 'provider_branch',
            },
        ),
    ]
