# Generated by Django 4.2.8 on 2025-05-21 14:38

import Admin.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_logo',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=Admin.models.shop_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), Admin.models.validate_image_size]),
        ),
    ]
