# Generated by Django 4.2.8 on 2025-05-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_shop_shop_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_topic',
        ),
    ]
