version: '3.9'

services:
  epaal-db:
    image: postgres:15
    container_name: epaal_db
    env_file:
      - ./.env-dev
    volumes:
      - epaal_pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  epaal-web:
    build: .
    command: gunicorn EvaamBack.wsgi:application --bind 0.0.0.0:8001 --log-level debug --access-logfile - --error-logfile -
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    env_file:
      - ./.env-dev
    depends_on:
      - epaal-db

volumes:
  epaal_pg_data:
  static_volume:
  media_volume:

