# Generated by Django 4.2.8 on 2024-11-24 21:40

import Product.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('discount', models.IntegerField(max_length=3)),
                ('is_in_event', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('num_of_seen', models.IntegerField(default=0)),
                ('is_confirm', models.BooleanField(default=False)),
                ('detail', models.CharField(max_length=500)),
                ('rate', models.IntegerField(default=0)),
                ('num_of_rates', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'product_color',
                'verbose_name_plural': 'product_colors',
                'db_table': 'product_color',
            },
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_pic', models.ImageField(blank=True, max_length=1000, null=True, upload_to=Product.models.product_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), Product.models.validate_image_size])),
            ],
            options={
                'verbose_name': 'product_picture',
                'verbose_name_plural': 'product_pictures',
                'db_table': 'product_picture',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'product_specification',
                'verbose_name_plural': 'Product_specifications',
                'db_table': 'product_specification',
            },
        ),
        migrations.CreateModel(
            name='ProductTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'product_topic',
                'verbose_name_plural': 'product_topics',
                'db_table': 'product_topic',
            },
        ),
    ]
