# Generated by Django 4.2.8 on 2025-02-23 00:18

import Product.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiledValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'field_value',
                'verbose_name_plural': 'field_values',
                'db_table': 'field_value',
            },
        ),
        migrations.CreateModel(
            name='LowlevelTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('picture', models.ImageField(blank=True, max_length=1000, null=True, upload_to=Product.models.lowlevel_topic_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), Product.models.validate_image_size])),
            ],
            options={
                'verbose_name': 'lowlevel_topic',
                'verbose_name_plural': 'lowlevel_topics',
                'db_table': 'lowlevel_topic',
            },
        ),
        migrations.CreateModel(
            name='MidlevelTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('picture', models.ImageField(blank=True, max_length=1000, null=True, upload_to=Product.models.midlevel_topic_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), Product.models.validate_image_size])),
                ('is_product', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'midlevel_topic',
                'verbose_name_plural': 'midlevel_topics',
                'db_table': 'midlevel_topic',
            },
        ),
        migrations.CreateModel(
            name='MidlevelTopicProviderBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'midlevel_topic_provider_branch',
                'verbose_name_plural': 'midlevel_topic_provider_branchs',
                'db_table': 'midlevel_topic_provider_branch',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_in_event', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('num_of_seen', models.IntegerField(default=0)),
                ('is_confirm', models.BooleanField(default=False)),
                ('detail', models.CharField(max_length=500)),
                ('rate', models.IntegerField(default=0)),
                ('num_of_rates', models.IntegerField(default=0)),
                ('admin_confirm', models.BooleanField(default=False)),
                ('report_message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_pic', models.ImageField(blank=True, max_length=1000, null=True, upload_to=Product.models.product_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), Product.models.validate_image_size])),
            ],
            options={
                'verbose_name': 'product_picture',
                'verbose_name_plural': 'product_pictures',
                'db_table': 'product_picture',
            },
        ),
        migrations.CreateModel(
            name='StaticField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField(default=0)),
                ('topic_level', models.IntegerField(default=None)),
                ('is_filter', models.BooleanField(default=False)),
                ('is_choosable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'static_field',
                'verbose_name_plural': 'static_fields',
                'db_table': 'static_field',
            },
        ),
        migrations.CreateModel(
            name='ToplevelTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('picture', models.ImageField(blank=True, max_length=1000, null=True, upload_to=Product.models.toplevel_topic_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), Product.models.validate_image_size])),
            ],
            options={
                'verbose_name': 'toplevel_topic',
                'verbose_name_plural': 'toplevel_topics',
                'db_table': 'toplevel_topic',
            },
        ),
        migrations.CreateModel(
            name='ProductTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('picture', models.ImageField(blank=True, max_length=1000, null=True, upload_to=Product.models.product_topic_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), Product.models.validate_image_size])),
                ('lowlevel_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_topic_lowlevel_topic', to='Product.lowleveltopic')),
            ],
            options={
                'verbose_name': 'product_topic',
                'verbose_name_plural': 'product_topics',
                'db_table': 'product_topic',
            },
        ),
        migrations.CreateModel(
            name='ProductStaticField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_static_field', to='Product.staticfield')),
                ('field_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_static_field', to='Product.filedvalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_static_field', to='Product.product')),
            ],
            options={
                'verbose_name': 'product_static_field',
                'verbose_name_plural': 'product_static_fields',
                'db_table': 'product_static_field',
            },
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('discount', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_instance', to='Product.product')),
            ],
            options={
                'verbose_name': 'product_instance',
                'verbose_name_plural': 'product_instances',
                'db_table': 'product_instance',
            },
        ),
        migrations.CreateModel(
            name='ProductDynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dynamic_field', to='Product.staticfield')),
                ('field_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dynamic_field', to='Product.filedvalue')),
                ('product_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dynamic_field', to='Product.productinstance')),
            ],
            options={
                'verbose_name': 'product_dynamic_field',
                'verbose_name_plural': 'product_dynamic_fields',
                'db_table': 'product_dynamic_field',
            },
        ),
    ]
