# Generated by Django 4.2.8 on 2025-01-07 12:44

import Product.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FiledValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'field_value',
                'verbose_name_plural': 'field_values',
                'db_table': 'field_value',
            },
        ),
        migrations.CreateModel(
            name='LowlevelTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('picture', models.ImageField(blank=True, max_length=1000, null=True, upload_to=Product.models.lowlevel_topic_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), Product.models.validate_image_size])),
            ],
            options={
                'verbose_name': 'lowlevel_topic',
                'verbose_name_plural': 'lowlevel_topics',
                'db_table': 'lowlevel_topic',
            },
        ),
        migrations.CreateModel(
            name='MidlevelTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('picture', models.ImageField(blank=True, max_length=1000, null=True, upload_to=Product.models.midlevel_topic_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), Product.models.validate_image_size])),
                ('is_product', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'midlevel_topic',
                'verbose_name_plural': 'midlevel_topics',
                'db_table': 'midlevel_topic',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('discount', models.IntegerField(max_length=3)),
                ('is_in_event', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('num_of_seen', models.IntegerField(default=0)),
                ('is_confirm', models.BooleanField(default=False)),
                ('detail', models.CharField(max_length=500)),
                ('rate', models.IntegerField(default=0)),
                ('num_of_rates', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'product_color',
                'verbose_name_plural': 'product_colors',
                'db_table': 'product_color',
            },
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_pic', models.ImageField(blank=True, max_length=1000, null=True, upload_to=Product.models.product_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), Product.models.validate_image_size])),
            ],
            options={
                'verbose_name': 'product_picture',
                'verbose_name_plural': 'product_pictures',
                'db_table': 'product_picture',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'product_specification',
                'verbose_name_plural': 'Product_specifications',
                'db_table': 'product_specification',
            },
        ),
        migrations.CreateModel(
            name='ToplevelTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('picture', models.ImageField(blank=True, max_length=1000, null=True, upload_to=Product.models.toplevel_topic_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), Product.models.validate_image_size])),
            ],
            options={
                'verbose_name': 'toplevel_topic',
                'verbose_name_plural': 'toplevel_topics',
                'db_table': 'toplevel_topic',
            },
        ),
        migrations.CreateModel(
            name='StaticField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField(default=0)),
                ('is_filter', models.BooleanField(default=False)),
                ('is_choosable', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'static_field',
                'verbose_name_plural': 'static_fields',
                'db_table': 'static_field',
            },
        ),
        migrations.CreateModel(
            name='ProductTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('picture', models.ImageField(blank=True, max_length=1000, null=True, upload_to=Product.models.product_topic_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), Product.models.validate_image_size])),
                ('lowlevel_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_topic_lowlevel_topic', to='Product.lowleveltopic')),
            ],
            options={
                'verbose_name': 'product_topic',
                'verbose_name_plural': 'product_topics',
                'db_table': 'product_topic',
            },
        ),
    ]
