# Generated by Django 4.2.8 on 2025-02-23 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        ('Admin', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.ManyToManyField(blank=True, null=True, to='Product.productpicture'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_product_topic', to='Product.producttopic'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_shop', to='Admin.shop'),
        ),
        migrations.AddField(
            model_name='midleveltopicproviderbranch',
            name='midlevel_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midlevel_topic_provider_branch', to='Product.midleveltopic'),
        ),
        migrations.AddField(
            model_name='midleveltopicproviderbranch',
            name='provider_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_branch_midlevel_topic', to='Admin.providerbranch'),
        ),
        migrations.AddField(
            model_name='midleveltopic',
            name='toplevel_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midlevel_toplevel', to='Product.topleveltopic'),
        ),
        migrations.AddField(
            model_name='lowleveltopic',
            name='midlevel_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowlevel_midlevel', to='Product.midleveltopic'),
        ),
        migrations.AddField(
            model_name='filedvalue',
            name='static_filed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_filed_value', to='Product.staticfield'),
        ),
    ]
