# Generated by Django 4.2.8 on 2024-11-24 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0001_initial'),
        ('Admin', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.ManyToManyField(blank=True, null=True, to='Product.productpicture'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_specification',
            field=models.ManyToManyField(blank=True, null=True, to='Product.productspecification'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_topic', to='Product.producttopic'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_of_titles', to='Admin.shop'),
        ),
        migrations.AddField(
            model_name='availableproduct',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availbal_product_color', to='Product.productcolor'),
        ),
        migrations.AddField(
            model_name='availableproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availbal_product', to='Product.product'),
        ),
    ]
