# Generated by Django 4.2.8 on 2024-12-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToplevelTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'toplevel_topic',
                'verbose_name_plural': 'toplevel_topics',
                'db_table': 'toplevel_topic',
            },
        ),
        migrations.CreateModel(
            name='MidlevelTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('toplevel_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midlevel_toplevel', to='Product.topleveltopic')),
            ],
            options={
                'verbose_name': 'midlevel_topic',
                'verbose_name_plural': 'midlevel_topics',
                'db_table': 'midlevel_topic',
            },
        ),
        migrations.AddField(
            model_name='producttopic',
            name='midlevel_topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_topic_midlevel_topic', to='Product.midleveltopic'),
            preserve_default=False,
        ),
    ]
