# Generated by Django 4.2.8 on 2025-02-26 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdynamicfield',
            name='field_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_dynamic_field', to='Product.filedvalue'),
        ),
        migrations.AlterField(
            model_name='productstaticfield',
            name='field_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_static_field', to='Product.filedvalue'),
        ),
    ]
