# Generated by Django 4.2.8 on 2025-01-07 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowleveltopic',
            name='midlevel_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowlevel_midlevel', to='Product.midleveltopic'),
        ),
    ]
