# Generated by Django 4.2.8 on 2025-04-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_productdynamicfield_field_value_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FiledValue',
            new_name='FieldValue',
        ),
    ]
