# Generated by Django 4.2.8 on 2025-01-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_lowleveltopic_midlevel_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticfield',
            name='content_type',
        ),
        migrations.AddField(
            model_name='staticfield',
            name='topic_level',
            field=models.IntegerField(default=None),
        ),
    ]
