# Generated by Django 4.2.8 on 2025-02-04 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_staticfield_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dynamic_field', to='Product.staticfield')),
                ('field_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dynamic_field', to='Product.filedvalue')),
            ],
            options={
                'verbose_name': 'product_dynamic_field',
                'verbose_name_plural': 'product_dynamic_fields',
                'db_table': 'product_dynamic_field',
            },
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('discount', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'product_instance',
                'verbose_name_plural': 'product_instances',
                'db_table': 'product_instance',
            },
        ),
        migrations.CreateModel(
            name='ProductStaticField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_static_field', to='Product.staticfield')),
                ('field_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_static_field', to='Product.filedvalue')),
            ],
            options={
                'verbose_name': 'product_static_field',
                'verbose_name_plural': 'product_static_fields',
                'db_table': 'product_static_field',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_specification',
        ),
        migrations.AddField(
            model_name='product',
            name='admin_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='report_message',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AvailableProduct',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
        migrations.AddField(
            model_name='productstaticfield',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_static_field', to='Product.product'),
        ),
        migrations.AddField(
            model_name='productinstance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_instance', to='Product.product'),
        ),
        migrations.AddField(
            model_name='productdynamicfield',
            name='product_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dynamic_field', to='Product.productinstance'),
        ),
    ]
