# Generated by Django 4.2.8 on 2025-04-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_remove_product_product_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
