# Generated by Django 4.2.8 on 2025-02-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_provider_providerbranch'),
        ('Product', '0005_productdynamicfield_productinstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midleveltopic',
            name='provider_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midlevel_provider_branch', to='Admin.providerbranch'),
        ),
    ]
