# Generated by Django 4.2.8 on 2025-04-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_product_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldvalue',
            old_name='static_filed',
            new_name='static_field',
        ),
    ]
