# Generated by Django 4.2.8 on 2025-02-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_provider_providerbranch'),
        ('Product', '0006_midleveltopic_provider_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midleveltopic',
            name='provider_branch',
        ),
        migrations.CreateModel(
            name='MidlevelTopicProviderBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midlevel_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midlevel_topic_provider_branch', to='Product.midleveltopic')),
                ('provider_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_branch_midlevel_topic', to='Admin.providerbranch')),
            ],
            options={
                'verbose_name': 'midlevel_topic_provider_branch',
                'verbose_name_plural': 'midlevel_topic_provider_branchs',
                'db_table': 'midlevel_topic_provider_branch',
            },
        ),
    ]
