# Generated by Django 4.2.8 on 2025-04-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_rename_static_filed_fieldvalue_static_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstaticfield',
            name='value',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
