# Generated by Django 4.2.8 on 2025-04-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_productstaticfield_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdynamicfield',
            name='value',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
