# Generated by Django 4.2.8 on 2025-06-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_productdynamicfield_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='report_message',
        ),
        migrations.AddField(
            model_name='product',
            name='reject_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
