# Generated by Django 4.2.8 on 2025-02-23 02:28

import Bank.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, max_length=1000, null=True, upload_to=Bank.models.bank_picture_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), Bank.models.validate_image_size])),
            ],
            options={
                'verbose_name': 'bank',
                'verbose_name_plural': 'banks',
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_value', models.CharField(max_length=100)),
                ('evaam_subscripton_percent', models.FloatField(default=3.5)),
                ('pre_payment_percent', models.FloatField(default=3.5)),
                ('bank_interest_percent', models.FloatField(default=23)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_id_facility', to='Bank.bank')),
            ],
            options={
                'verbose_name': 'facility',
                'verbose_name_plural': 'facilities',
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='FacilityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_id_facility_document', to='Bank.facility')),
            ],
            options={
                'verbose_name': 'facility_document',
                'verbose_name_plural': 'facility_documents',
                'db_table': 'facility_document',
            },
        ),
    ]
