# Generated by Django 4.2.8 on 2025-02-23 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityInstallmentNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_installment', models.IntegerField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_id_facility_installment_number', to='Bank.facility')),
            ],
            options={
                'verbose_name': 'facility_installment_number',
                'verbose_name_plural': 'facility_installment_numbers',
                'db_table': 'facility_installment_number',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_id_sub_grade', to='Bank.grade')),
            ],
        ),
        migrations.CreateModel(
            name='UserFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('max_value', models.CharField(max_length=100)),
                ('evaam_subscripton_percent', models.FloatField(default=3.5)),
                ('pre_payment_percent', models.FloatField(default=3.5)),
                ('bank_interest_percent', models.FloatField(default=23)),
                ('level', models.CharField(max_length=100)),
                ('level_number', models.IntegerField()),
                ('choosen_value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choosen_facility_installment_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_installment_number_id_user_facility', to='Bank.facilityinstallmentnumber')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_id_user_facility', to='Bank.facility')),
                ('sub_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_grade_id_user_facility', to='Bank.subgrade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_user_facility', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_facility',
                'verbose_name_plural': 'user_facilities',
                'db_table': 'user_facility',
            },
        ),
    ]
