# Generated by Django 4.2.8 on 2025-02-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_facilityinstallmentnumber_grade_subgrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfacility',
            name='shaba_number',
            field=models.CharField(default='', max_length=26),
            preserve_default=False,
        ),
    ]
