# Generated by Django 4.2.8 on 2025-02-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_userfacility_shaba_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfacility',
            name='shaba_number',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
