# Generated by Django 4.2.8 on 2025-02-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_alter_userfacility_shaba_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfacility',
            old_name='shaba_number',
            new_name='sheba_number',
        ),
    ]
