# Generated by Django 4.2.8 on 2025-02-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0005_rename_shaba_number_userfacility_sheba_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='jiibit_bank_naem',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
