# Generated by Django 4.2.8 on 2025-02-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0006_bank_jiibit_bank_naem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
