# Generated by Django 4.2.8 on 2025-02-25 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0007_bank_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfacility',
            name='sub_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_grade_id_user_facility', to='Bank.subgrade'),
        ),
    ]
