# Generated by Django 4.2.8 on 2025-02-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0008_alter_userfacility_sub_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfacility',
            name='given_value',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
