# Generated by Django 4.2.8 on 2025-02-25 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0009_userfacility_given_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocumetn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, max_length=1000, null=True, upload_to='Media/user_document/')),
                ('stutus', models.CharField(max_length=100)),
                ('problem_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_document_id_user_document', to='Bank.facilitydocument')),
                ('user_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_facility_id_user_document', to='Bank.userfacility')),
            ],
            options={
                'verbose_name': 'user_document',
                'verbose_name_plural': 'user_documents',
                'db_table': 'user_document',
            },
        ),
    ]
