# Generated by Django 4.2.8 on 2025-02-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0010_userdocumetn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdocumetn',
            old_name='stutus',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='userdocumetn',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
