# Generated by Django 4.2.8 on 2025-02-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0011_rename_stutus_userdocumetn_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfacility',
            name='reject_reason_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
