# Generated by Django 4.2.8 on 2025-02-26 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0012_userfacility_reject_reason_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.FloatField()),
                ('final_amount', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=100)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_facility_id_user_installment', to='Bank.userfacility')),
            ],
            options={
                'verbose_name': 'user_installment',
                'verbose_name_plural': 'user_installments',
                'db_table': 'user_installment',
            },
        ),
    ]
