# Generated by Django 4.2.8 on 2025-02-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0013_userinstallment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstallment',
            name='status',
            field=models.CharField(default='not_paid', max_length=100),
        ),
    ]
