# Generated by Django 4.2.8 on 2024-11-24 21:40

import Blog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('is_show', models.BooleanField(default=False)),
                ('is_top', models.BooleanField(default=False)),
                ('num_of_like', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'blog_comment',
                'verbose_name_plural': 'blog_comments',
                'db_table': 'blog_comment',
            },
        ),
        migrations.CreateModel(
            name='BlogPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_pic', models.ImageField(blank=True, max_length=1000, null=True, upload_to=Blog.models.blog_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), Blog.models.validate_image_size])),
            ],
            options={
                'verbose_name': 'blog_picture',
                'verbose_name_plural': 'blog_pictures',
                'db_table': 'blog_picture',
            },
        ),
        migrations.CreateModel(
            name='BlogTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'blog_topic',
                'verbose_name_plural': 'blog_topics',
                'db_table': 'blog_topic',
            },
        ),
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_id_userblog', to='Blog.blog')),
            ],
            options={
                'verbose_name': 'blog_user',
                'verbose_name_plural': 'blog_users',
                'db_table': 'blog_user',
            },
        ),
    ]
