# Generated by Django 4.2.8 on 2025-04-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255, verbose_name='Shop Name')),
                ('first_name', models.CharField(max_length=255, verbose_name='Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('site_url', models.URLField(max_length=255, verbose_name='Site URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Is Confirmed')),
            ],
            options={
                'verbose_name': 'Shop Request',
                'verbose_name_plural': 'Shop Requests',
            },
        ),
    ]
