# Generated by Django 4.2.8 on 2025-05-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoprequest',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='shoprequest',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='shop_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='site_url',
            field=models.URLField(max_length=255),
        ),
    ]
