# Generated by Django 4.2.8 on 2024-11-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('otp_code', models.CharField(max_length=8)),
                ('otp_expire', models.DateTimeField()),
                ('max_try', models.IntegerField(default=3, max_length=2)),
            ],
            options={
                'verbose_name': 'otp',
                'verbose_name_plural': 'otps',
                'db_table': 'otp',
            },
        ),
    ]
