# Generated by Django 4.2.8 on 2025-02-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
