# Generated by Django 4.2.8 on 2024-11-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='top_for',
            field=models.CharField(default='login', max_length=50),
        ),
    ]
