# Generated by Django 4.2.8 on 2025-02-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_customuser_shamsi_birthday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
