# Generated by Django 4.2.8 on 2024-11-25 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_otp_top_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='top_for',
            new_name='otp_for',
        ),
    ]
