# Generated by Django 4.2.8 on 2025-02-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_customuser_birthday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-24 17:57:14.146830'),
            preserve_default=False,
        ),
    ]
