# Generated by Django 4.2.8 on 2024-12-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_rename_top_for_otp_otp_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
