# Generated by Django 4.2.8 on 2025-02-25 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_address_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credit_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'credit_wallet',
                'verbose_name_plural': 'credit_wallets',
                'db_table': 'credit_wallet',
            },
        ),
        migrations.CreateModel(
            name='UserCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_wallet_id_user_credit_transaction', to='User.creditwallet')),
            ],
            options={
                'verbose_name': 'user_credit_transaction',
                'verbose_name_plural': 'user_credit_transactions',
                'db_table': 'user_credit_transaction',
            },
        ),
    ]
