# Generated by Django 4.2.8 on 2025-02-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_creditwallet_usercredittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredittransaction',
            name='is_booster',
            field=models.BooleanField(default=False),
        ),
    ]
