# Generated by Django 4.2.8 on 2024-11-24 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Transaction', '0002_initial'),
        ('User', '0001_initial'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'cart', 'verbose_name_plural': 'carts'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_id_cart', to='Product.product'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_price', models.IntegerField(max_length=30)),
                ('delivery_price', models.IntegerField(max_length=30)),
                ('status', models.CharField(max_length=50)),
                ('num_of_product', models.IntegerField(default=1)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_id_order', to='User.address')),
                ('products', models.ManyToManyField(related_name='product_ids_order', to='Product.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_id_order', to='Transaction.tranaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='BoughtOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_discount', models.IntegerField(max_length=3)),
                ('all_discount', models.IntegerField(max_length=3)),
                ('product_cost', models.IntegerField(max_length=30)),
                ('paid_cost', models.IntegerField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id_bought_order', to='Order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id_bought_order', to='Product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_bought_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bought_order',
                'verbose_name_plural': 'bought_orders',
                'db_table': 'bought_order',
            },
        ),
    ]
