# Generated by Django 4.2.8 on 2025-02-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_productdynamicfield_field_value_and_more'),
        ('Order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_id_cart', to='Product.productinstance'),
        ),
    ]
