# Generated by Django 4.2.8 on 2025-04-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_productdynamicfield_value'),
        ('Order', '0003_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id_bought_order', to='Product.productinstance'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='product_ids_order', to='Product.productinstance'),
        ),
    ]
