# Generated by Django 4.2.8 on 2025-04-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_boughtorder_product_alter_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boughtorder',
            old_name='product',
            new_name='product_intance',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product_intances',
        ),
    ]
