# Generated by Django 4.2.8 on 2025-04-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_usercredittransaction_is_booster'),
        ('Order', '0005_rename_product_boughtorder_product_intance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_id_order', to='User.usercredittransaction'),
        ),
    ]
