# Generated by Django 4.2.8 on 2025-05-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_productdynamicfield_value'),
        ('Order', '0006_alter_order_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_id_cart_item', to='Order.cart')),
                ('product_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_instance_id_cart_item', to='Product.productinstance')),
            ],
            options={
                'verbose_name': 'cart_item',
                'verbose_name_plural': 'cart_items',
                'db_table': 'cart_item',
            },
        ),
    ]
