# Generated by Django 4.2.8 on 2025-05-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_remove_cart_products_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_intances',
        ),
        migrations.AddField(
            model_name='boughtorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
